name: Build and release Nosana Node brew package

on:
  push:
    tags:
      - v*

jobs:
  build_release:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        # os: [ ubuntu-latest, macos-latest ]
        os: [ ubuntu-latest ]

    steps:
      # repo
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      # java
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # clojure
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: latest

      # clj
      - name: Clojure check
        run: clojure --version

      # build
      - name: Clojure Uber Build
        run: clojure -X:compile uberjar

      # artifact
      - name: '[${{ runner.os }}] Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: nosana-node-${{ runner.os }}
          path: target/*.jar
          if-no-files-found: error
